CREATE TABLE IF NOT EXISTS venues (
  id          BIGSERIAL PRIMARY KEY,
  name        TEXT NOT NULL UNIQUE,
  category    TEXT NOT NULL DEFAULT 'Store',
  district    TEXT,
  website     TEXT
);


INSERT INTO venues (name, category, district, website)
VALUES
  ('Åhlens', 'Store', 'Öster', 'https://ahlens.se/varuhus/jonkoping?utm_source=google&utm_medium=organic&utm_campaign=business_profile&utm_content=website_link'),
  ('Akademibokhandeln', 'Store', 'Öster', 'https://akademibokhandeln.se/butik/jonkoping-c'),
  ('Apoteket AB', 'Store', NULL, 'https://apoteket.se/apotek/apoteket-ostra-storgatan-jonkoping/'),
  ('Apotek Hjärtat', 'Store', NULL, 'https://apotekhjartat.se/hitta-apotek-hjartat/jonkoping/apotek_hjartat_smedjegatan_2_jonkoping/'),
  ('Ashur Brud & Fest - Skrädderi', 'Store', NULL, 'https://facebook.com/AshuraitaBrudFest/'),
  ('Asia livs, servicebutik', 'Store', NULL, 'https://facebook.com/profile.php?id=100051215441977'),
  ('Ateljé Creativ i Jönköping/Finrummet', 'Store', 'Väster', 'https:///finrummet.net'),
  ('Ateljé KEG', 'Store', 'Öster', 'https://ateljekeg.se'),
  ('Atlantis Dive College', 'Store', 'Väster', 'https://atlantis.se'),
  ('Bagelle väskboutique', 'Store', NULL, NULL),
  ('Balance Ljud och Bild', 'Store', NULL, 'https://balance.se'),
  ('BGA Fotocenter', 'Store', 'Öster', 'https://bgafotocenter.se/jonkoping/'),
  ('Bikupan', 'Store', 'Tändsticksområdet', 'https://bikupan.org'),
  ('Blankdays', 'Store', 'Tändsticksområdet', 'https://blankdays.com/collections/all-products?gclid=CjwKCAjwov6hBhBsEiwAvrvN6EZZ1PsnlSJhnE7bmxINtl0Y0noU3rvCybdt217CGd3-bqMdx3mYRxoCK5EQAvD_BwE'),
  ('Boardlife', 'Store', 'Väster', 'https://boardlife.se'),
  ('Borgs skor', 'Store', 'Öster', 'https://borgsskor.se/kontakt'),
  ('Boutique Lykka', 'Store', 'Öster', 'https://boutiquelykka.se'),
  ('Broder Bläck', 'Store', 'Öster', 'https://facebook.com/broderblacktatuering/'),
  ('Buketten', 'Store', 'Öster', 'https://instagram.com/bukettenjonkoping/?hl=sv'),
  ('Busfrö Nytt & Bytt', 'Store', 'Öster', 'https://busfro.se'),
  ('Butiken Noga Utvalt', 'Store', 'Atollen', 'https://butikenjkpg.se'),
  ('Carlings', 'Store', 'Öster', 'https://carlings.com/sv/corporate/Butiker/sweden/58f/'),
  ('Casa Souk', 'Store', 'Väster', 'https://casasouk.se'),
  ('Cervera', 'Store', 'Öster', 'https://cervera.se/hitta-butik/'),
  ('Clas Ohlson', 'Store', 'Öster', 'https://clasohlson.com/se/store-finder?q=J%C3%B6nk%C3%B6ping,%20City&latitude=57.78252&longitude=14.17347&source=search'),
  ('Coop Atollen', 'Store', 'Atollen', 'https://coop.se/butiker-erbjudanden/coop/coop-atollen-jonkoping/'),
  ('Coop Östra Torget', 'Store', 'Öster', 'https://coop.se/butiker-erbjudanden/coop/coop-ostra-torget/'),
  ('Copenhagen Luxe', 'Store', 'Öster', 'https://copenhagenluxe.dk/'),
  ('Day fotografi', 'Store', NULL, 'https://dayfotografi.se/'),
  ('Dinos kemtvätt', 'Store', 'Väster', 'https://dinos.nu'),
  ('Din Sko', 'Store', 'Öster', 'https://dinsko.se/stores'),
  ('Direkt optik', 'Store', NULL, 'https://www.direktoptik.se/butiker/jonkoping/ostra-storgatan-29/'),
  ('Dressman', 'Store', 'Öster', 'https://dressmann.com/no/bedriftssider/finn-butikk/Sweden/Dressmann_Jonkoping/'),
  ('Elias Urmästare', 'Store', NULL, 'https://facebook.com/profile.php?id=100064073112753'),
  ('Engströms Urmakeri', 'Store', NULL, 'https://engstromsurmakeri.se'),
  ('Euroex', 'Store', NULL, NULL),
  ('Evoke industry', 'Store', NULL, NULL),
  ('Fabriken', 'Store', 'Atollen', 'https://butikfabriken.se'),
  ('Fiction Prescription', 'Store', NULL, 'https://www.instagram.com/fiction.prescription.jonkoping/'),
  ('Forex Bank Väster', 'Store', 'Väster', NULL),
  ('Foten', 'Store', NULL, 'https://www.foten.se/'),
  ('Friendly Corner', 'Store', 'Tändsticksområdet', 'https://friendlycorner.se/butiken'),
  ('Galleri 701 ramcenter', 'Store', NULL, 'https://galleri701-ram.se'),
  ('Gant', 'Store', 'Atollen', 'https://gant.se/stores?lat=57.78261370000001&long=14.1617876&postalCode=j%C3%B6nk%C3%B6ping&radius=10.0'),
  ('Gåvan', 'Store', 'Öster', 'https://gavanjonkoping.se'),
  ('Gina Tricot', 'Store', 'Öster', 'https://ginatricot.com/se/find-store'),
  ('Go Banana', 'Store', 'Väster', 'https://gobanana.se'),
  ('Godis och Tobakshörnan', 'Store', 'Öster', NULL),
  ('Golden athlete', 'Store', 'Öster', 'https://goldenathlete.se/sv/butiker-2'),
  ('Grmawit Store', 'Store', 'Väster', 'https://grmawit.com/'),
  ('Guldsmedjan Snarberg', 'Store', 'Väster', 'https://guldsmedjan-snarberg.se'),
  ('Hälsokraft', 'Store', 'Öster', 'https://halsokraft.se/butiker?butik=503'),
  ('Hemköp', 'Store', 'Väster', 'https://hemkop.se/butik/4674'),
  ('Hemmakväll', 'Store', 'Öster', 'https://hemmakvall.se/hitta-butik/'),
  ('Hemtex', 'Store', 'Öster', 'https://hemtex.se/hitta-butik/jonkoping'),
  ('Hi-fi Klubben', 'Store', 'Väster', 'https://hifiklubben.se/hitta-butik/jonkoping/?gclid=Cj0KCQjwhsmaBhCvARIsAIbEbH4w2ngSDzygBKQSqHVzCSFAplyrpByCMojT6dfo-Xnjcn7P9j_jBn8aAsD0EALw_wcB'),
  ('H&M', 'Store', 'Öster', 'https://hm.com/sv_se/customer-service/shoppa-pa-hm/store-locator'),
  ('H&M Home', 'Store', 'Öster', 'https://hm.com/sv_se/customer-service/shoppa-pa-hm/store-locator'),
  ('Indiska', 'Store', 'Öster', 'https://indiska.com/se/butiker'),
  ('Jeansshoppen', 'Store', 'Öster', 'https://jeansshopen.se/sv/kontakt'),
  ('JL Sycenter', 'Store', NULL, 'https://jlsycenter.se/kontakta-oss/'),
  ('Jönköpings antik och konsthandel', 'Store', 'Väster', NULL),
  ('Jönköpings Cigrarrimport', 'Store', NULL, 'https://atg.se/jonkopingscigarrimport'),
  ('KappAhl', 'Store', 'Öster', 'https://www.kappahl.com/sv-SE/kundservice/kundservice/hitta-butik/'),
  ('Karin Lund Design', 'Store', NULL, 'https://facebook.com/karinlunddesign/'),
  ('Katrin Bååths Ateljé', 'Store', 'Tändsticksområdet', 'https://katrinbaath.se/ateljen/'),
  ('Kicks', 'Store', 'Öster', 'https://kicks.se/butiker/jonkoping-smedjegatan'),
  ('Kjell & Company', 'Store', 'Öster', 'https://kjell.com/se/butiker/sodra-strandgatan-5'),
  ('Klädscoopet', 'Store', 'Öster', 'https://facebook.com/Kladscoopet/'),
  ('KOiJ Konsthantverk', 'Store', 'Öster', 'https://koij.se'),
  ('Kristina Brud & Fest', 'Store', 'Väster', 'https://kristinabrud-fest.se'),
  ('Kronans Apotek Atollen', 'Store', 'Atollen', 'https://apoteksinfo.nu/apotek/kronans_apotek_atollen_j%C3%B6nk%C3%B6ping-1415'),
  ('Kvänum Kök', 'Store', 'Öster', 'https://kvanum.com/se/showrooms/jonkoping/'),
  ('Lagerhaus', 'Store', 'Öster', 'https://lagerhaus.se/stores'),
  ('Lavér Studio', 'Store', NULL, 'https://laverstudio.com/'),
  ('Life Naturlig Hälsa', 'Store', 'Väster', 'https://www.lifebutiken.se/stores'),
  ('Lilla Violen', 'Store', 'Väster', 'https://lillaviolen.com/'),
  ('Lindex', 'Store', 'Öster', 'https://lindex.com/se/hitta-din-butik?location=57.756066%2C14.188254&storeId=002&zoom=11'),
  ('Livspotential Kroppsterapi', 'Store', NULL, 'https://facebook.com/Livspotential/'),
  ('Lloyd Tabing Art Gallery', 'Store', 'Tändsticksområdet', 'https://lloydtabingart.com/'),
  ('Macforum', 'Store', 'Öster', 'https://macforum.se/butiker/forum-jonkoping'),
  ('MarQet', 'Store', 'Öster', 'https://mq.se/butiker/?gclid=Cj0KCQjwteOaBhDuARIsADBqRejM-U3YQY9vh4F6gSXC2LnJWPVGKJ7CGfiCl1tYkREGUR37cTWMNcoaAjFGEALw_wcB'),
  ('Mimosa City', 'Store', NULL, 'https://mimosacity.se'),
  ('Moderna Smycken', 'Store', 'Öster', 'https://klockorochsmycken.se/'),
  ('Naturkompaniet', 'Store', 'Öster', 'https://murphysbar.se/sv/'),
  ('Newhouse', 'Store', 'Atollen', 'https://newhouse.se/newhouse/vara-butiker'),
  ('New Yorker', 'Store', 'Öster', 'https://newyorker.de/se/stores/'),
  ('Nilson Shoes', 'Store', 'Öster', 'https://dinsko.se/stores'),
  ('Noa Noa', 'Store', 'Öster', 'https://httpsfacebook.com/Noa-Noa-J%C3%B6nk%C3%B6ping-446212958766553/'),
  ('Nordisk Möbelkonst', 'Store', 'Öster', 'https://nordiskmobelkonst.se/'),
  ('Normal', 'Store', 'Öster', 'https://normal.se/hitta-butik/'),
  ('Nya Musik', 'Store', 'Väster', 'https://nyamusik.se/'),
  ('Once for girls', 'Store', 'Öster', 'https://oncestore.se/'),
  ('Önska', 'Store', 'Öster', 'https://onska.se/vara-butiker/'),
  ('Optiker Jahnke', 'Store', 'Öster', 'https://jahnke.se/'),
  ('Optiker Ullström', 'Store', 'Väster', 'https://optikerullstrom.se/'),
  ('Optik & Form', 'Store', NULL, 'https://optikochform.se/'),
  ('Partyland', 'Store', 'Väster', 'https://partyland.party/butiker/'),
  ('Planta Blommor', 'Store', 'Väster', 'https://plantablommor.se/?gclid=Cj0KCQjwteOaBhDuARIsADBqRehsWXSRNHjeGnPn_AyambJZLmNntWxsMnUkANIHdme0NoDtc2Xi8mgaAicoEALw_wcB#.Y2p1tuzMLPZ'),
  ('Pleasure erotic shop', 'Store', 'Väster', 'https://pleasureeroticshop.se/'),
  ('PMU Second Hand Jönköping City', 'Store', 'Öster', 'https://pmu.se/stores/jonkopingcity/'),
  ('Pressbyrån Östra storgatan', 'Store', 'Öster', 'https://pressbyran.se/kontakt/hitta-butik/'),
  ('Pressbyrån Resecentrum', 'Store', 'Resecentrum', 'https://pressbyran.se/kontakt/hitta-butik/'),
  ('Pressbyrån Väster', 'Store', 'Väster', 'https://pressbyran.se/kontakt/hitta-butik/'),
  ('Rabalder', 'Store', 'Öster', 'https://publik.rabalder.se/butiker/joenkoeping.aspx'),
  ('Resehuset', 'Store', 'Väster', 'https://resehuset.se/'),
  ('Rituals', 'Store', 'Öster', 'https://rituals.com/sv-se/store-detail?store=J%C3%B6nk%C3%B6ping-%C3%96stra-Storgatan'),
  ('Rizzo', 'Store', 'Öster', 'https://rizzo.se/stores/'),
  ('Röda Korset Second Hand', 'Store', 'Väster', 'https://rodakorset.se/vad-vi-gor/second-hand/butiker/roda-korset-secondhand-jonkoping/?gclid=CjwKCAjwzY2bBhB6EiwAPpUpZvHzKjPuEJP8mzdhkuZYuEUoinVduEX8lEL6C0cnHq-JkG5o4XalYBoCwX8QAvD_BwE'),
  ('Rundquist & Zälle', 'Store', 'Väster', 'https://rundquist-zalle.com'),
  ('Säfvers Tobak', 'Store', NULL, 'https://facebook.com/people/S%C3%A4fvers-tobak/100049803762896/'),
  ('SåIniNordeN', 'Store', 'Öster', 'https://saininorden.se/'),
  ('Sandströms', 'Store', 'Öster', 'https://sandstroms.nu/butiker/sandstroms-jonkoping'),
  ('Sarabello', 'Store', 'Öster', 'https://facebook.com/people/SARABELLO/100054240470073/'),
  ('Saumas sko & nyckelservice', 'Store', NULL, 'https://saumasskoochnyckelservice.heymo.se/'),
  ('Sjöqvists skomakeri', 'Store', 'Väster', 'https://sjoqvistskomakeri.se/'),
  ('Smålands Skinnmanufaktur', 'Store', 'Tändsticksområdet', 'https://smalandsskinnmanufaktur.se/'),
  ('Smarteyes', 'Store', NULL, 'https://smarteyes.se/butiker/jonkoping'),
  ('Smycka Guld', 'Store', NULL, 'https://smycka.se/store/19'),
  ('Smycket', 'Store', NULL, 'https://smycketjonkoping.se/'),
  ('Specsavers', 'Store', NULL, 'https://httpspecsavers.se/hitta-till-din-butik/jonkoping-city?utm_source=google&utm_medium=organic&utm_campaign=gmb-website&utm_content=jonkoping&y_source=1_NDA4Nzk2NjQtNzE1LWxvY2F0aW9uLndlYnNpdGU%3D'),
  ('Stagelight', 'Store', NULL, 'https://stagelight.se/'),
  ('Stil', 'Store', 'Öster', 'https://stilbutikerna.se/'),
  ('Story', 'Store', 'Atollen', 'https://storyjkpg.se'),
  ('SunOff', 'Store', 'Väster', 'https://sunoff.se/butiker/jonkoping?gclid=CjwKCAjw8JKbBhBYEiwAs3sxNy3EnUFGceeFxyJN35fymdpsg5qEWUTPj6Sx0TbNoLdwp8E6AI-I5xoC45gQAvD_BwE'),
  ('Synoptik', 'Store', NULL, 'https://httpsynoptik.se/butiker/jonkoping/jonkoping-ostra-storgatan5?utm_campaign=gmb-website&utm_source=google&utm_medium=organic&utm_content=667-Jonkoping-Ostra-Storgatan-5'),
  ('Synsam Jönköping Öster', 'Store', 'Öster', 'https://synsam.se/optiker/synsam-j%C3%B6nk%C3%B6ping-%C3%B6ster/128'),
  ('Synsam Jönköping Väster', 'Store', 'Väster', 'https://synsam.se/optiker/synsam-j%C3%B6nk%C3%B6ping-v%C3%A4ster/125'),
  ('Systembolaget', 'Store', 'Öster', 'https://systembolaget.se/butiker-ombud/'),
  ('The Body Shop', 'Store', 'Öster', 'https://thebodyshop.com/sv-se/store-details/jonkoping-smedjegatan/3801?utm_source=google&utm_medium=organic-local&utm_campaign=yext&utm_content=3801'),
  ('Ticket', 'Store', NULL, 'https://ticket.se/resebutiker/jonkoping.html'),
  ('Twilfit', 'Store', 'Öster', 'https://shop.change.com/sv-SE'),
  ('Ur & Penn', 'Store', 'Öster', 'https://uropenn.se/hitta-butik/'),
  ('Västanhem Butik', 'Store', 'Väster', 'https://vastanhem.se'),
  ('Västra klackbaren', 'Store', NULL, NULL),
  ('Vätterbygden Ankarbergs Begravningsbyrå', 'Store', NULL, 'https://ankarbergs.se/'),
  ('Vätterfisk', 'Store', 'Väster', 'https://xn--vtterfisk-v2a.se/'),
  ('Yxhage Lås och Larm', 'Store', NULL, 'https://yxhage.se/'),
  ('Zephyr Tattoo Parlour', 'Store', 'Öster', 'https://zephyrtattoo.se')
ON CONFLICT (name) DO NOTHING;
